### ISSUE TITLE
QR Code Generator

### ISSUE THREAD

**Issue by soham4abc** [GDSC-RCCIIT/General-Purpose-Scripts#10]
### Describe the new script you want
User will input a link and the script returns a QR code of that link

### Describe the solution you'd like us to follow
A python script is preferable

## Do you want to work on this?
- [ ] yes
- [x] no

### Additional context
Add any other context or screenshots about the feature request here. If not applicable remove this section.

**Comment by danger-ahead** [comment]
Hi. Can I work on this issue?

**Comment by OBITORASU** [comment]
Yes feel free to work on this!
