### ISSUE TITLE
Meter-to-Feet-Converter

### ISSUE THREAD

**Issue by aaryan078** [GDSC-RCCIIT/General-Purpose-Scripts#100]
### Describe the new script you want
A script that converts meter to Feet.

### Describe the solution you'd like us to follow
A python script to convert Meter-to-Feet-Converter using python modules.

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by OBITORASU** [comment]
This is too common you can just go to google and have it done, a dedicated script doesn't make much sense. Closing this.
