### ISSUE TITLE
Terminal Video Editor

### ISSUE THREAD

**Issue by belelaritra** [GDSC-RCCIIT/General-Purpose-Scripts#101]
## Terminal Video Editor
Edit Videos (specifically : `.mp4`) directly from the terminal.

### Describe the new script you want
<b>Functionalities :</b>
* Trim Video (From: beginning / ending)
* Remove a portion from the Video
* Resize the Video (By: %)
* Control the speed of the Video (Fast / Slow)
* Control the volume (Increase / Decrease)
* Extract Audio from Video
* and other functionalities

### Describe the solution you'd like us to follow
Use [Moviepy](https://pypi.org/project/moviepy) library to edit videos.

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by belelaritra** [comment]
@OBITORASU , @rijusougata13 👋
<b>Please assign this issue to me.</b> 😊

**Comment by OBITORASU** [comment]
Sure go ahead.
