### ISSUE TITLE
pie chart maker

### ISSUE THREAD

**Issue by AcousticCh** [GDSC-RCCIIT/General-Purpose-Scripts#106]
### Describe the new script you want
A clear and concise description of what the new script is all about. Ex. I want an email script which [...]
I want to add a python command line script that parses a list of user input and displays it on a pie chart

### Describe the solution you'd like us to follow
A clear and concise description of how you want this script to work.

## Do you want to work on this?
- [x ] yes
- [ ] no

### Additional context
Add any other context or screenshots about the feature request here. If not applicable remove this section.

**Comment by OBITORASU** [comment]
Go ahead! Make sure the user input is valid though.
