### ISSUE TITLE
Hangman Game

### ISSUE THREAD

**Issue by imsushant12** [GDSC-RCCIIT/General-Purpose-Scripts#108]
### Describe the new script you want
I want to implement a script of the famous hangman game.

### Describe the solution you'd like us to follow
My script will be a famous game named hangman which can be played between 2 players.

## Do you want to work on this?
- [YES] yes
- [ ] no

**Comment by SaheliThakur** [comment]
Hi, I'd like to contribute to this script.  I would be implementing this game using a python script which could be played between two players.

**Comment by OBITORASU** [comment]
This script is just a game and doesn't really automate anything in general so I will consider this invalid.
