### ISSUE TITLE
YouTube Video Downloader

### ISSUE THREAD

**Issue by soham4abc** [GDSC-RCCIIT/General-Purpose-Scripts#11]
### Describe the solution you'd like us to follow
You can use any python package you want just mention it in the README and requirements.txt

## Do you want to work on this?
- [ ] yes
- [x] no

### Additional context
Add any other context or screenshots about the feature request here. If not applicable remove this section.

**Comment by belelaritra** [comment]
I like to work on this issue.

**Comment by OBITORASU** [comment]
I am sorry but I cannot pickup this script request because downloading videos off of YouTube is a direct breach of their ToS currently.
