### ISSUE TITLE
Scrape Tweets of a Hashtag using Twitter API

### ISSUE THREAD

**Issue by dishant26** [GDSC-RCCIIT/General-Purpose-Scripts#110]
### Describe the new script you want
I will create a script to scrape tweets of a user-inputted Hashtag

### Describe the solution you'd like us to follow
This will be a command line script, it will initially ask the user to input the Hashtag and then it will scrape the 100-200 most recent tweets of that Hashtag using the Twitter API and Tweepy and will then create a csv file of all those tweets for the user.

## Do you want to work on this?
- [x] yes
- [ ] no

### Additional context
Add any other context or screenshots about the feature request here. If not applicable remove this section.

**Comment by OBITORASU** [comment]
Go ahead! Make sure you document this well for the end-user.

**Comment by Kashika18** [comment]
I would like to work on this issue, please assign it to me.
