### ISSUE TITLE
Audio Transcriptor

### ISSUE THREAD

**Issue by Monish-P** [GDSC-RCCIIT/General-Purpose-Scripts#113]
## Suggest a new script for the project
 
Audio Transcriptor
### Describe the new script you want

This python script will convert an audio file to text and also uses speech recognition to convert our speech to text. Lastly, the text is saved in a new separate file.

### Describe the solution you'd like us to follow

I will be using some python modules like pydub, speech recognition to work on this. Also I will be using file handling with python.

Please assign me this isue.

**Comment by OBITORASU** [comment]
Go ahead!
