### ISSUE TITLE
Colored Image to Sketch Converter

### ISSUE THREAD

**Issue by deepak-chouhan** [GDSC-RCCIIT/General-Purpose-Scripts#115]
## Suggest a new script for the project
Python Image Converter

### Describe the new script you want
I want to add a Python Script which will Convert Colored Image to Sketch Image

### Describe the solution you'd like us to follow
I will user OpenCV library to convert Image to Sketch Image

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by OBITORASU** [comment]
Go ahead!

**Comment by Ritika457** [comment]
Hey, @deepak-chouhan can you please assign this issue to me. I can work on this.

**Comment by rijusougata13** [comment]
> Hey, @deepak-chouhan can you please assign this issue to me. I can work on this.

Hi @Ritika457 , @deepak-chouhan  is currently working on this.

**Comment by Kashika18** [comment]
@deepak-chouhan  I would like to work on the issue, please assign it to me.

**Comment by deepak-chouhan** [comment]
@Kashika18 i have already raised a pull request for this issue, you can raise an issue for another script which you want to work on. A maintainer will assign you that issue and then you can start working on it
