### ISSUE TITLE
Audio format converter

### ISSUE THREAD

**Issue by DCYPHERR** [GDSC-RCCIIT/General-Purpose-Scripts#119]
## Suggest a new script for the project
Audio format converter

## Do you want to work on this?
- [ x] yes

**Comment by Shashwat-05** [comment]
- [x] yes, can you please assign this to me, This will be going to be my very first hacktober contribution.

**Comment by DCYPHERR** [comment]
I recently finished it so I'd like to contribute it to this repository for everyone to use. Hence why I've raised the issue. Sorry!

**Comment by rijusougata13** [comment]
go ahead

**Comment by OBITORASU** [comment]
> - [x] yes, can you please assign this to me, This will be going to be my very first hacktober contribution. @DCYPHERR 

You can open another issue and have it assigned.

**Comment by OBITORASU** [comment]
@Shashwat-05  still interested in working on this?

**Comment by Shashwat-05** [comment]
so I'm a bit confused, is this script hasn't it been completed properly?

**Comment by OBITORASU** [comment]
@Shashwat-05 the assignee closed his pull request and the issue which implies he doesn't wanna work on it anymore making this script an up-for-grab script request.

**Comment by Shashwat-05** [comment]
Yes, I'll be glad to work on it. @OBITORASU

**Comment by OBITORASU** [comment]
Go ahead!

**Comment by SanjanaSogimatt** [comment]
Can I work on this project? I am new to open source

**Comment by SanjanaSogimatt** [comment]
Extremely sorry for the disturbance .It's an audio format converter so it is supposed to convert audio into any other format. So I was thinking to use inbuilt library pydub for this project. But this can only convert into to a single type like mp3. Is it okay?

**Comment by DCYPHERR** [comment]
> Extremely sorry for the disturbance .It's an audio format converter so it is supposed to convert audio into any other format. So I was thinking to use inbuilt library pydub for this project. But this can only convert into to a single type like mp3. Is it okay?

Originally I planned to take in any type of audio file identify its format, then provide the user a selection of multiple formats to convert it to.

**Comment by OBITORASU** [comment]
> Extremely sorry for the disturbance .It's an audio format converter so it is supposed to convert audio into any other format. So I was thinking to use inbuilt library pydub for this project. But this can only convert into to a single type like mp3. Is it okay?

You are kind of wrong on the conversion type. `pydub` defaults to `.mp3` when exporting but natively supports `.wav` and `.raw` as well. For rest of the audio formats though you have to install `ffmpeg` as a dependency on the system.
