### ISSUE TITLE
Newsdown is using a vulnerable version of the Pillow library

### ISSUE THREAD

**Issue by OBITORASU** [GDSC-RCCIIT/General-Purpose-Scripts#12]
### Mention the script affected by the bug
Newsdown

### Describe the bug
Newsdown is vulnerable to a DoS attack because of a vulnerable dependency in it namely Pillow version < 8.3.2.

### To Reproduce
Check the Pillow version in requirements.txt you will notice there is an advisory out for it being vulnerable

### Expected behavior
We should be using a patched version of Pillow

## Do you want to work on this?
- [ ] yes
- [x] no

### Additional context
The solution should be pretty simple, bump the dependency to `pillow>=8.3.2` in the requirements.txt and make sure the script works and runs properly with the new dependency bump.

**Comment by bartick** [comment]
Can I work on it?

**Comment by OBITORASU** [comment]
Sure thing
