### ISSUE TITLE
Filters files through their extension

### ISSUE THREAD

**Issue by st0rm2** [GDSC-RCCIIT/General-Purpose-Scripts#121]
### Describe the new script you want
I want an python script that filters files by their extension.

### Describe the solution you'd like us to follow
It will filter the files with a similar extension and moving it to a new folder that is dedicated to files of that extension.

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by rijusougata13** [comment]
go ahead

**Comment by OBITORASU** [comment]
I think we already have one such script called file organizer.
