### ISSUE TITLE
Calculate the Duration of any YouTube playlist

### ISSUE THREAD

**Issue by dishant26** [GDSC-RCCIIT/General-Purpose-Scripts#128]
### Describe the new script you want
The main issue in YouTube is  that it does not show the total time duration of any playlist. 
I will create a script to calculate the time duration of any YouTube playlist.

### Describe the solution you'd like us to follow
Initially the user will enter the playlist link for which the user want the time duration. I will use Google Cloud Console's YouTubeAPI to scrape to all video details in the playlist to calculate the time duration.

## Do you want to work on this?
- [x] yes
- [ ] no

### Additional context
Add any other context or screenshots about the feature request here. If not applicable remove this section.

**Comment by OBITORASU** [comment]
Go ahead you can work on this!

**Comment by OBITORASU** [comment]
Make sure you document this one well.

**Comment by ShivamS2201** [comment]
Can I work on this too?
