### ISSUE TITLE
Password Strength Checker

### ISSUE THREAD

**Issue by rex2828** [GDSC-RCCIIT/General-Purpose-Scripts#129]
### Describe the new script you want
Basically this script will tell how many times the password has been breached before in data breaches so you can estimate the strength of a password

### Describe the solution you'd like us to follow
I am using an API for fetching of haveibeenpwned.com to bring the data, and make sure you don't have to enter your password directly on the site for more security.

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by rex2828** [comment]
can I work on this issue?

**Comment by OBITORASU** [comment]
Yes you can work on this!

**Comment by rex2828** [comment]
Hey @OBITORASU can you look at this PR, and merge it if correct.

**Comment by tausiq2003** [comment]
can I work on this
