### ISSUE TITLE
Newsdown has unused imports

### ISSUE THREAD

**Issue by OBITORASU** [GDSC-RCCIIT/General-Purpose-Scripts#14]
### Mention the script affected by the bug
Newsdown

### Describe the bug
The script seems to have imported a few things which were never really used in the script itself.

### Expected behavior
Unused imports should be removed and the script should be tested at least once to see if it runs after the changes.

## Do you want to work on this?
- [ ] yes
- [x] no

**Comment by bartick** [comment]
I would I to work on it

**Comment by OBITORASU** [comment]
Sure feel free!
