### ISSUE TITLE
secured chat machine with encryption

### ISSUE THREAD

**Issue by Dr-blue-cyber** [GDSC-RCCIIT/General-Purpose-Scripts#141]
# secured chat machine with encyption

## Do you want to work on this?
- [X] yes
- [ ]  no

**Comment by OBITORASU** [comment]
@rijusougata13 opinions?

**Comment by rijusougata13** [comment]
interesting !! go ahead

**Comment by Dr-blue-cyber** [comment]
hello @rijusougata13  @OBITORASU  just what I mentioned I make push requests with branch name Chat_Machine If there is any problems or suggest your opinion to me plz..

**Comment by Dr-blue-cyber** [comment]
hello @rijusougata13  @OBITORASU  can anyone here to tell me what happened to my merge request plz I need your suggestions

**Comment by OBITORASU** [comment]
@Dr-blue-cyber you didn't create one to begin with as far as I see.

**Comment by rijusougata13** [comment]
hi. Please send your PR. Then we can review. I guess changes on your local machine.

**Comment by Dr-blue-cyber** [comment]
<img width="960" alt="Screenshot 2021-10-05 000348" src="https://user-images.githubusercontent.com/85605208/135905584-9e3025bb-0e51-42b0-bc8e-3d6b54174771.png">



bro after lots of efforts i did this plz see this screenshot if there is any mistakes plz let mw know @rijusougata13 @OBITORASU

**Comment by OBITORASU** [comment]
You are yet to open a pull request, I suggest you read our contributing guidelines on how you can or just watch a youtube video.

**Comment by rijusougata13** [comment]
hi currently the PR is under your origin. You have to send the pr to our repo. To do that click compare and send pull request. Fill the template. click commit .
