### ISSUE TITLE
Simple ceaser cipher encoder, decoder

### ISSUE THREAD

**Issue by st0rm2** [GDSC-RCCIIT/General-Purpose-Scripts#146]
### Describe the new script you want
I want  python script that implements the simple ceaser cipher encoder and decoder

### Describe the solution you'd like us to follow
A clear and concise description of how you want this script to work.

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by OBITORASU** [comment]
Go ahead!

**Comment by AntrikshSharma** [comment]
I would like to work on this! :)

**Comment by khushboorathore10** [comment]
Hi I would like to work on this issue ... Kindly assign this to me @st0rm2
