### ISSUE TITLE
Random email generator

### ISSUE THREAD

**Issue by jadhav-kunal** [GDSC-RCCIIT/General-Purpose-Scripts#147]
## Suggest a new script for the project
Random email generator

### Describe the new script you want
This script will randomly generate an email address using a mix of letters, both caps on and off, numbers, and punctuation, then outputs the results.

### Describe the solution you'd like us to follow
- Script will ask user for how many emails they want generated. Must be Integer.
- Creates emails.
- Also displays progress bar.

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by yashpy** [comment]
I would like to contribute to this issue. I ll fix it.

**Comment by OBITORASU** [comment]
Can you please tell me how this idea might be useful?
