### ISSUE TITLE
Downloading MiniClip Games using a Python Script

### ISSUE THREAD

**Issue by GigaMoksh** [GDSC-RCCIIT/General-Purpose-Scripts#148]
## Suggest a new script for the project
Python Script which downloads all the miniclip games 

### Describe the new script you want
I'll be using bs4 to parse miniclip website and download all the games that are present on the website. Also, we will be using os module to create a folder for all of this games.

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by yashpy** [comment]
Please assign me this work.

**Comment by OBITORASU** [comment]
I don't feel like this script is that useful for general purpose use, specifically because it sounds like a one time use script. Closing this.
