### ISSUE TITLE
Vaccination details checker script

### ISSUE THREAD

**Issue by soham4abc** [GDSC-RCCIIT/General-Purpose-Scripts#15]
### Describe the new script you want
Government API can be used to fetch the details of the vaccination center.

### Describe the solution you'd like us to follow
Use python script to view the available vaccine slots preferably use PIN code to get nearest location.

## Do you want to work on this?
- [ ] yes
- [x] no

Stakeholders- @OBITORASU

**Comment by belelaritra** [comment]
I like to work on this issue.

**Comment by belelaritra** [comment]
I would like to work on this issue.

**Comment by OBITORASU** [comment]
Assigning this to you @belelaritra. Have fun!
