### ISSUE TITLE
Covid Cases Tracker

### ISSUE THREAD

**Issue by GigaMoksh** [GDSC-RCCIIT/General-Purpose-Scripts#150]
## Suggest a new script for the project
Check total cases, total deaths or total recovered from covid in a specific country or in the whole world.

### Describe the new script you want
I'll be using a GUI which will show how many cases are there in the specific country you searched for or even the total cases in the whole world. Also, we can check total deaths and total recovered from covid19

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by OBITORASU** [comment]
Go ahead!

**Comment by GigaMoksh** [comment]
thankyou!
