### ISSUE TITLE
Keylogger

### ISSUE THREAD

**Issue by jadhav-kunal** [GDSC-RCCIIT/General-Purpose-Scripts#159]
## Suggest a new script for the project
Keylogger

### Describe the new script you want
Keylogger script will be written in python and it will log input from the keyboard.

## Do you want to work on this?
- [x] yes
- [ ] no

### Additional context

It can be used by employers to monitor activity of employees.
It can also be used by teachers to monitor activity of students.

**Comment by jadhav-kunal** [comment]
@OBITORASU Can you please assign me?

**Comment by OBITORASU** [comment]
How do you wish to transmit the logs of this keylogger can you explain?

**Comment by jadhav-kunal** [comment]
Logs will be stored in logs.txt using write function in python

**Comment by OBITORASU** [comment]
Go ahead.

**Comment by MrRobot3301** [comment]
Hi, 
This is MrRobot, Please assign this to me. I'll Make it !
