### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by GigaMoksh** [GDSC-RCCIIT/General-Purpose-Scripts#160]
![GDSC-RCCIIT_General-Purpose-Scripts_ A repository containing several general purpose Python scripts to automate daily and common tasks  - Google Chrome 04-10-2021 16_05_06](https://user-images.githubusercontent.com/72140092/135836941-e1a51116-51e3-43e6-8507-d02484ed1034.png)

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by advaita-saha** [comment]
Assign me

**Comment by rijusougata13** [comment]
Hi, We found that it's a small change. An extra space caused this. Thanks for reporting. But we will not accept any pr for this as it's a one-line fix.

**Comment by Candida18** [comment]
Please assign this issue to me, there are many scripts which have been added to the repo but not mentioned in the readme
