### ISSUE TITLE
Correct the inconsistency in the README file

### ISSUE THREAD

**Issue by advaita-saha** [GDSC-RCCIIT/General-Purpose-Scripts#161]
### Mention the script affected by the bug
main Readme.md file inconsistency

## Do you want to work on this?
- [x] yes
- [ ] no

<img width="931" alt="Screenshot 2021-10-04 at 3 56 47 PM" src="https://user-images.githubusercontent.com/30210770/135837612-5d6486c9-4a6a-4c23-92ef-dab4ab8d2b4d.png">

### Additional context
Add any other context about the problem here. If not applicable remove this section.

**Comment by GigaMoksh** [comment]
I have already opened the issue for this.

**Comment by bartick** [comment]
There is already a issue on this #130 . Please don't open duplicate issues.

**Comment by rijusougata13** [comment]
Hi, We found that it's a small change. An extra space caused this. Thanks for reporting. But we will not accept any pr for this as it's a one-line fix.
