### ISSUE TITLE
Crypto Currency

### ISSUE THREAD

**Issue by jayaganeshkumar** [GDSC-RCCIIT/General-Purpose-Scripts#17]
### Describe the new script you want
In this script, we will see all the details of cryptocurrency at the instinct of time. Also, if we want to know about a particular crypto coin then it will add those details too. All these details will be stored in a CSV file.

I have used selenium and beautiful soup to do so.

## Do you want to work on this?
- [X] yes
- [ ] no

**Comment by OBITORASU** [comment]
Sounds good! Assigning this to you.

**Comment by jayaganeshkumar** [comment]
Thanks man
