### ISSUE TITLE
LinkedIn Job Scrapper 

### ISSUE THREAD

**Issue by belelaritra** [GDSC-RCCIIT/General-Purpose-Scripts#170]
## Suggest a new script for the project
LinkedIn Job Scrapper 

### Describe the new script you want
Scrap best fitted job details according to your location & your job profile.

### Describe the solution you'd like us to follow
Without using any API or, python libraries like [`linkedin-scraper`](https://pypi.org/project/linkedin-scraper/).

## Do you want to work on this?
- [x] yes
- [ ] no

### Additional context
Add any other context or screenshots about the feature request here. If not applicable remove this section.

**Comment by OBITORASU** [comment]
Go ahead!
