### ISSUE TITLE
Text Encryption and Decryption to and from an Image (Steganography)

### ISSUE THREAD

**Issue by Candida18** [GDSC-RCCIIT/General-Purpose-Scripts#179]
# Text Encryption and Decryption to and from an Image (Steganography)

## Description
A script to encode or hide text into an image and then decode it.

## Description of the solution 
* Upload the image in which you want to encrypt text
* Write the function to perform encryption
* Text will be encrypted into the image
* Write the function to perform decryption
* Display the text encrypted in the image.

## Do you want to work on this?
- [x] yes
- [ ] no

## Additional context
This feature can be used to integrate face-recognition into an email system; where the email and password can be encrypted into ones captured face

**Comment by OBITORASU** [comment]
Make this such that the user selects and image file locally via the command line or menu instead of having a upload feature. Make sure its a `.py` script instead of a notebook file :)

**Comment by nipunarora8** [comment]
Please assign this task to me, I will complete it.

**Comment by OBITORASU** [comment]
Are you still working on this issue?
