### ISSUE TITLE
Live video workout tracking. 

### ISSUE THREAD

**Issue by nipunarora8** [GDSC-RCCIIT/General-Purpose-Scripts#184]
Live video workout tracking. 

A pose detection-based workout-tracking script that can demonstrate workout on a live video as well as on a stick diagram. 

The user will stand in front of the camera and perform movements and using pose estimation the algorithm will be able to show him his performance. 
Additionally, will map the movement of the elbow and shoulder joints with angles for better understanding.

## Do you want to work on this?
- yes

**Comment by rijusougata13** [comment]
go ahead @nipunarora8

**Comment by OBITORASU** [comment]
@nipunarora8 really sorry for the delay in reviewing your PR. Thanks for your contribution. 

Issue closed by PR #198
