### ISSUE TITLE
Inshort Short news scrapper.

### ISSUE THREAD

**Issue by harshrawat20** [GDSC-RCCIIT/General-Purpose-Scripts#189]
## Suggest a new script for the project
Inshort Short news scrapper.

### Describe the new script you want
The program will consist of a scrapper which scraps the short news from the inshorts website.

### Describe the solution you'd like us to follow
This will simply just scrap the information from the website(https://www.inshorts.com/en/read) and show on the output screen.

## Do you want to work on this?
- [*] yes
- [ ] no

**Comment by OBITORASU** [comment]
We already have two news scrapers on our repository so closing this one. Feel free to open up another script request if you have some other nice idea!
