### ISSUE TITLE
Check Disk and CPU Usage

### ISSUE THREAD

**Issue by adviksinghania** [GDSC-RCCIIT/General-Purpose-Scripts#19]
### Describe the new script you want
A Python3 script to get free space percentage of local disks and average CPU usage over a period of time, using inbuilt modules.

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by OBITORASU** [comment]
Great idea assigning this to you!

**Comment by ignaviaa** [comment]
hi , i would like to take this up.

**Comment by ignaviaa** [comment]
hi , i would like to work on it.

**Comment by OBITORASU** [comment]
This one is already assigned sadly, please open up a new issue if you have a new script idea and I shall have it assigned to you!

**Comment by ignaviaa** [comment]
ah okay.
