### ISSUE TITLE
Create bar graph using python code

### ISSUE THREAD

**Issue by PradeepBaipadithaya** [GDSC-RCCIIT/General-Purpose-Scripts#196]
### Describe the new script you want
This code takes the points as input and returns the bar graph representation.

**Comment by PradeepBaipadithaya** [comment]
Please assign me with this issue

**Comment by sippuutkarsh** [comment]
i am good at solving these type of issues . can you please assign it to me

**Comment by akash9579** [comment]
Hi Pradeep
Can you assigned me this issue?
i will make user interactive bar graph as well

**Comment by OBITORASU** [comment]
@PradeepBaipadithaya are you still working?

**Comment by sonikasahoo** [comment]
Hi,this is my 1st contribution.  Can you please assign me this issue?
You can also check my profile .
