### ISSUE TITLE
Update main README.md

### ISSUE THREAD

**Issue by Candida18** [GDSC-RCCIIT/General-Purpose-Scripts#199]
### Mention the Script where you would like to have this feature added
General-Purpose-Scripts README.md

### Describe the solution you'd like
Please assign this issue to me, there are many scripts which have been added to the repo but not mentioned in the readme

I would also sort the list of scripts table in the main README.md

## Do you want to work on this?
- [x] yes
- [ ] no

### Additional context
There many scripts which are missing in the main documentation. I would add them and also sort the list of scripts in ascending order

**Comment by OBITORASU** [comment]
Go ahead.
