### ISSUE TITLE
URL-Shortener Script Request

### ISSUE THREAD

**Issue by GawdOfROFL** [GDSC-RCCIIT/General-Purpose-Scripts#2]
### Describe the new script you want
I want an url shortener script

### Describe the solution you'd like us to follow
Instead of using an API, we can query a site with requests module and parse the response for the shortened url.

## Do you want to work on this?
- [ ] yes
- [x] no

**Comment by soham4abc** [comment]
I am willing to work on this issue can I have it assigned?

**Comment by OBITORASU** [comment]
Sure go ahead feel free to work on it!
