### ISSUE TITLE
Links in readme are broken.

### ISSUE THREAD

**Issue by OBITORASU** [GDSC-RCCIIT/General-Purpose-Scripts#218]
### Mention the script affected by the bug
The main readme file of our repository.

### Describe the bug
A lot of the links in the available scripts section of our main readme file are either broken or are pointing to something entirely off-topic. 

### Expected behavior
Ideally all the links should work and point to the directory of the target script.

## Do you want to work on this?
- [ ] yes
- [x] no

## Additional Context
You have to check all the links and fix the broken ones.

**Comment by Oaparecido** [comment]
Hey, can you assign this issue to me ?!

**Comment by OBITORASU** [comment]
Sure!
