### ISSUE TITLE
a weather forecast script based on latitude and longitude

### ISSUE THREAD

**Issue by dawnblade97** [GDSC-RCCIIT/General-Purpose-Scripts#22]
### Describe the new script you want
A simple script that would forecast the weather depending on the city given by user

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by OBITORASU** [comment]
Nice idea assigning this to you!

**Comment by adityamittl** [comment]
I would like to work upon this

**Comment by OBITORASU** [comment]
Sorry but this is already assigned to @dawnblade97
