### ISSUE TITLE
Move .type of files from one folder to another.

### ISSUE THREAD

**Issue by GigaMoksh** [GDSC-RCCIIT/General-Purpose-Scripts#220]
## Suggest a new script for the project
This script automatically moves the type of file you provide from the source folder to the destionation folder you provided.

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by OBITORASU** [comment]
Don't feel like this is very useful, this is a simple command in bash and on Windows it should be a simple drag and drop.
