### ISSUE TITLE
News Scraping Script

### ISSUE THREAD

**Issue by pragyakhanna11** [GDSC-RCCIIT/General-Purpose-Scripts#231]
### Describe the new script you want
I want to add a web scraping script which scrapes news website and makes a csv as well as a doc for the same

### Describe the solution you'd like us to follow
I would like to use beautifulSoup for this project

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by OBITORASU** [comment]
We already have two news scrapers on our repository. Closing this.
