### ISSUE TITLE
External IP Address

### ISSUE THREAD

**Issue by OjusWiZard** [GDSC-RCCIIT/General-Purpose-Scripts#24]
### Describe the new script you want
It will be a python code to make a request to [http://checkip.dyndns.org](http://checkip.dyndns.org), which in turn send a response back with your External IP address.

This response will be in HTML so it will also extract only useful information from it and print it as an output.

### Describe the solution you'd like us to follow
It only needs to get executed using a python3 interpreter.
```bash
python scripts/Public\ IP\ Address/my_public_ip.py
```

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by OBITORASU** [comment]
Maybe you should follow the text and add some real description about what you want to do? You didn't even bother changing the template...

**Comment by OjusWiZard** [comment]
Yeah just realized, I wrote the context but for some reason, it just submitted the template.
I resubmitted it now 👍

**Comment by OBITORASU** [comment]
Sure go ahead work on this

**Comment by OBITORASU** [comment]
Dont forget to follow the contributing guidelines :)
