### ISSUE TITLE
Typing speed test

### ISSUE THREAD

**Issue by lovishprabhakar** [GDSC-RCCIIT/General-Purpose-Scripts#252]
## Suggest a new script for the project
Typing speed tester using python

### Describe the new script you want
I want to add a script for a typing speed tester GUI which will tell users their typing speed.

## Do you want to work on this?
-  yes

**Comment by OBITORASU** [comment]
@lovishprabhakar02 why did you close the PR?

**Comment by Shubhi-22** [comment]
I want to add a script for a typing test tester which will tell user there typing speed and how there typing speed is like rating wise using GUI. I want to work on this.

**Comment by lovishprabhakar02** [comment]
@OBITORASU sir all problems have been solved in PR #272. Kindly review and merge it.

**Comment by OBITORASU** [comment]
> @OBITORASU sir all problems have been solved in PR #272. Kindly review and merge it.

Left you a review check.
