### ISSUE TITLE
Spam-bot

### ISSUE THREAD

**Issue by Shah-Aayush** [GDSC-RCCIIT/General-Purpose-Scripts#255]
## Suggest a new script for the project
Spam-bot : spams text-messages to anywhere !

### Describe the new script you want
I would like to add an spam-bot which can spam the text-messages as directed by user.

### Describe the solution you'd like us to follow
simple python script which asks user the text-message and number of count for spamming. [can spam infinite times too]
> I'll go for `pyautogui`

## Do you want to work on this?
- [X] yes
- [ ] no

**Comment by Shah-Aayush** [comment]
I have already requested a PR yesterday which was closed as I didn't create a new issue regarding this topic but now As I  created a new issue here, should I make a new PR or my existing closed PR can be opened?

**Comment by OBITORASU** [comment]
Spamming anyone/anything is mostly an unethical act and is a form of harassment. Sorry we cannot accept this script in our repository.
