### ISSUE TITLE
Script for Competitive Programming template maker

### ISSUE THREAD

**Issue by Kaustuv942** [GDSC-RCCIIT/General-Purpose-Scripts#26]
### Describe the new script you want
A script to organize contest code files in cpp for linux users.

### Describe the solution you'd like us to follow
Bash script

## Do you want to work on this?
- [x] yes
- [ ] no

### Additional context
Add any other context or screenshots about the feature request here. If not applicable remove this section.

**Comment by rijusougata13** [comment]
go ahead @Kaustuv942 !
