### ISSUE TITLE
Random-Password Generator

### ISSUE THREAD

**Issue by rijusougata13** [GDSC-RCCIIT/General-Purpose-Scripts#3]
### Describe the new script you want
I want a script that will generate random Passwords for me to help my online safety.

### Describe the solution you'd like us to follow
We can use the random module to randomize the password every time. Scripts that support storage with encryption for generated passwords should be given higher priority.

## Do you want to work on this?
- [ ] yes
- [x] no

**Comment by kriptonian1** [comment]
I would like to work in this issue

**Comment by yashjain-99** [comment]
I would like to work on this issue. It will be great opportunity for me.

**Comment by OBITORASU** [comment]
> 
> 
> I would like to work on this issue. It will be great opportunity for me.

@kriptonian1 is still working on this, his previous PR was closed due to a corrupted git history, so he made another PR for the same.

**Comment by avyayjain** [comment]
pls assign me this issue

**Comment by OBITORASU** [comment]
We already have an ongoing PR for this.

**Comment by Prajakta102** [comment]
kindly assign this task to me.

**Comment by OBITORASU** [comment]
Read above

**Comment by Ritika457** [comment]
Hey, @rijusougata13  can you assign this issue to me. I can fix this.

**Comment by Ritika457** [comment]
Hey, @rijusougata13  can you assign this issue to me? I can fix this.

**Comment by tausiq2003** [comment]
wait I will make a pr which have short code.

**Comment by KulkarniKrishna** [comment]
hey! please can you assign me, I would love to contribute

**Comment by Kashika18** [comment]
I would like to work on this issue, please assign this issue to me.

**Comment by avyayjain** [comment]
@rijusougata13 pls assign me this issue
