### ISSUE TITLE
Know your password

### ISSUE THREAD

**Issue by Kashika18** [GDSC-RCCIIT/General-Purpose-Scripts#313]
## Suggest a new script for the project
A python script that will let you know the already saved wifi passwords on your system.

## Do you want to work on this?
- [x] yes
- [ ] no

Please assign this issue to me under hacktoberfest.

**Comment by sonikasahoo** [comment]
Can you please label this as hackotober-fest and assign me this?
I want to contribute in this project.

**Comment by OBITORASU** [comment]
You can work on this if can you make this platform independent. You have to make sure it works on NT, Darwin and Linux.
