### ISSUE TITLE
Mindfulness- a mental health bot

### ISSUE THREAD

**Issue by Kashika18** [GDSC-RCCIIT/General-Purpose-Scripts#315]
## Suggest a new script for the project
A discord bot made using simple python script. 

### Describe the new script you want
It is a bot that detects sad messages and tries to increase the enthusiasm of the unhappy. The bot even provides some inspirational quotes as well as helpline numbers for people in great mental distress.

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by OBITORASU** [comment]
Discord bots aren't accepted sorry..
