### ISSUE TITLE
Download Youtube Videos

### ISSUE THREAD

**Issue by Kashika18** [GDSC-RCCIIT/General-Purpose-Scripts#316]
## Suggest a new script for the project
A youtube video downloader script using pytube

## Do you want to work on this?
- [x] yes
- [ ] no

Please assign this to me under hacktoberfest.

**Comment by MrRobot3301** [comment]
Hello , 
Please assign this issue to me i want to contribute on this. 
#MrRobot3301

**Comment by MrRobot3301** [comment]
Hello ,
Please assign this issue to me i want to contribute on this.
#MrRobot3301

**Comment by OBITORASU** [comment]
YouTube Terms of Service.

**Comment by MrRobot3301** [comment]
Ohh yes sure ! No prob ....
