### ISSUE TITLE
Add a pie chart also

### ISSUE THREAD

**Issue by thelokipost** [GDSC-RCCIIT/General-Purpose-Scripts#328]
## Suggest an improvement for a script
A pie chart would be great along with this. 

### Mention the Script where you would like to have this feature added
Name of the script where you want the feature.
In progran itself. 

### Describe the solution you'd like
An addition of pie chart would be helpful. 

## Do you want to work on this?
- [ ] yes
- [n ] no

### Additional context
Add any other context or screenshots about the feature request here. If not applicable remove this section.

**Comment by OBITORASU** [comment]
Which script are you trying to improve?
