### ISSUE TITLE
 Screen Recorder 

### ISSUE THREAD

**Issue by aaryan078** [GDSC-RCCIIT/General-Purpose-Scripts#344]
## Suggest a new script for the project

Screen Recorder using python
### Describe the new script you want
A clear and concise description of what the new script is all about. Ex. I want an email script which [...]
Build a Screen Recorder using python

## Do you want to work on this?
- [x] yes
- [ ] no

### Additional context
Add any other context or screenshots about the feature request here. If not applicable remove this section.

**Comment by OBITORASU** [comment]
We already have this one.
