### ISSUE TITLE
Text to audio convertor

### ISSUE THREAD

**Issue by lovishprabhakar** [GDSC-RCCIIT/General-Purpose-Scripts#361]
## Suggest a new script for the project
Text to audio using python.

### Describe the new script you want
I  would like to add  a script under hacktoberfest that takes some text as input and then makes the computer speak that text.(Just like an AI)

## Do you want to work on this?
- [ ] yes

**Comment by lovishprabhakar** [comment]
This issue isn't stale. The issue has been solved jn #365. @OBITORASU

**Comment by OBITORASU** [comment]
> This issue isn't stale. The issue has been solved jn #365. @OBITORASU 

It is marked stale because of inactivity GitHub does that automatically don't worry.
