### ISSUE TITLE
PDF Audiobook Reader

### ISSUE THREAD

**Issue by ignaviaa** [GDSC-RCCIIT/General-Purpose-Scripts#37]
### Describe the new script you want
A script that converts pdf texts-to-speech.

## Do you want to work on this?
- [x] yes
- [ ] no

### Additional context
A python script to convert text-to-speech using python modules.

**Comment by rijusougata13** [comment]
go ahead @ignaviaa

**Comment by OBITORASU** [comment]
Feel free to work on this!

**Comment by akash-rao-2001** [comment]
[text_to_speech.zip](https://github.com/GDSC-RCCIIT/General-Purpose-Scripts/files/7271865/text_to_speech.zip)

**Comment by OBITORASU** [comment]
@akash-rao-2001 this is clearly not how things work on `GitHub`. I suggest you watch a few YouTube tutorials about Git & GitHub and how to create PRs and Issues on GitHub.

**Comment by akash-rao-2001** [comment]
may i be assigned this issue

**Comment by OBITORASU** [comment]
> 
> 
> may i be assigned this issue

No this one is already assigned to @ignaviaa and we have an ongoing PR for that already. You are free to open up a new issue with some new script idea and I will have it assigned to you :)

**Comment by Ritika457** [comment]
Hey, @ignaviaa can you assign this issue to me. I can fix this.

**Comment by ignaviaa** [comment]
@Ritika457  sorry this issue has been already assigned to me and i have already pulled a request on it. But you are free to open up a new issue with some new script ideas and our maintainers will have it assigned to you.
