### ISSUE TITLE
Email-Phone Number Extractor

### ISSUE THREAD

**Issue by gitshashwat** [GDSC-RCCIIT/General-Purpose-Scripts#39]
### Describe the new script you want
Extract emails and phone numbers from the text of clipboard copied
or an input file and creates two csvs for it having email and phone number separately.

## Do you want to work on this?
- [x] yes
- [ ] no.

**Comment by rajatkeshri** [comment]
Hi, I will work on it. Can you assign it to me?

**Comment by rijusougata13** [comment]
@rajatkeshri  sorry !! @gitshashwat is working on this. If you want to contribute in this repo you can create an issue and I'll assign you there.
