### ISSUE TITLE
Newspaper  Downloader

### ISSUE THREAD

**Issue by IamBikramPurkait** [GDSC-RCCIIT/General-Purpose-Scripts#4]
### Describe the new script you want
You can download the newspaper on any date you want.

### Describe the solution you'd like us to follow
It made by tkinter and it can scrap the official newspaper website and download the image and make a pdf for any date.

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by OBITORASU** [comment]
Great idea assigning this to you!
