### ISSUE TITLE
Script to fetch lyrics of a song

### ISSUE THREAD

**Issue by adviksinghania** [GDSC-RCCIIT/General-Purpose-Scripts#40]
### Describe the new script you want
A Python3 script using Genius API to fetch the lyrics of a song given as input and store it in a text file.

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by belelaritra** [comment]
I would like to work on this.

**Comment by OBITORASU** [comment]
Nice idea go ahead

**Comment by saaiiravi** [comment]
Can I work on this as well?

**Comment by OBITORASU** [comment]
No this one has already been assigned.
