### ISSUE TITLE
Amazon-price-alert

### ISSUE THREAD

**Issue by adityamittl** [GDSC-RCCIIT/General-Purpose-Scripts#41]
### Describe the new script you want
The script that alerts the customer when the price of an amazon product is below the threshold price value

### Describe the solution you'd like us to follow
Using web scraping we can make an alert for the customer to get the product when they get the fair deal 

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by OBITORASU** [comment]
Great idea feel free to work on this.
