### ISSUE TITLE
Certificate Generator

### ISSUE THREAD

**Issue by FireQueen-3010** [GDSC-RCCIIT/General-Purpose-Scripts#43]
### Describe the new script you want
A python based certificate generator

### Describe the solution you'd like us to follow
A script template can be uploaded and gmail credentials of the sender needs to be inputted, also name and email of the participants can be stored in a file and this script will use translate property to place the name(s) in a place according to the template when run all the certificates are generated and automatically sent to the respective emails.

## Do you want to work on this?
- [x] yes
- [ ] no

### Additional context
Add any other context or screenshots about the feature request here. If not applicable remove this section.

**Comment by FireQueen-3010** [comment]
Please assign this me under hacktoberfest

**Comment by OBITORASU** [comment]
Go ahead!

**Comment by FlyingwithCaptainSoumya** [comment]
@OBITORASU  Can I work on this?

**Comment by Ollie-beep-bop** [comment]
@OBITORASU Can I contribute to this? i am new to hacktober so i needed to start with this. Thanking in advance

**Comment by MrRobot3301** [comment]
can u please assign this to me to contibute

**Comment by OBITORASU** [comment]
@FlyingwithCaptainSoumya you can work on this if you are interested, the original assignee didn't open a PR with us and hence was unassigned due to inactivity.
