### ISSUE TITLE
Grammar Checker and Corrector

### ISSUE THREAD

**Issue by rajatkeshri** [GDSC-RCCIIT/General-Purpose-Scripts#44]
### The grammatical issues will be found using the language tool API. (https://languagetool.org/)
Further the script will update the sentences based on the correction the API suggests. 

## Do you want to work on this?

- [x] yes

- [ ] no

Add any other context or screenshots about the feature request here. If not applicable remove this section.

**Comment by rajatkeshri** [comment]
Please assign me the task

**Comment by OBITORASU** [comment]
Sure go ahead!
