### ISSUE TITLE
OSINT Tool

### ISSUE THREAD

**Issue by kriptonian1** [GDSC-RCCIIT/General-Purpose-Scripts#45]
## Suggest a new script for the project
OSINT Tool to find phone number and IP address info

### Describe the new script you want
Use python modules to find information about IP address and phone number to help in OSINT investigation 

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by kriptonian1** [comment]
I would like to work in this issue

**Comment by OBITORASU** [comment]
Accepted! You can work on this.

**Comment by Ritika457** [comment]
Hey, @kriptonian1 can you assign this issue to me. I can fix this.
