### ISSUE TITLE
Threaded Port Scanner

### ISSUE THREAD

**Issue by adityamittl** [GDSC-RCCIIT/General-Purpose-Scripts#50]
## Suggest a new script for the project
A python script that searches for open ports for an IP address

### Describe the solution you'd like us to follow
A python script using socket, threading, argparse.

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by OBITORASU** [comment]
Can you make this script a threaded script for faster port scanning? Also I would request you to focus on the CLI aspect and use `argparse` for parsing command line arguments instead of making this menu driven. Are you willing to work within the above constraints?

**Comment by adityamittl** [comment]
Yes I would like to work on this

**Comment by OBITORASU** [comment]
Fine then go ahead!

**Comment by OBITORASU** [comment]
All yours!
