### ISSUE TITLE
Automatic Screen Recorder

### ISSUE THREAD

**Issue by Ahana134** [GDSC-RCCIIT/General-Purpose-Scripts#55]
## Suggest a new script for the project
**A python script that will automatically record our laptop screen** 

### Describe the new script you want
**We can record our screen automatically at any interval of time using python which is very helpful for online study purpose.**

### Describe the solution you'd like us to follow
Some python modules is required ,the dimensions of the screen will be provided .

## Do you want to work on this?

- [x] yes

- [ ] no

**Comment by Ahana134** [comment]
Please assign this task to me

**Comment by rijusougata13** [comment]
go ahead @Ahana134
