### ISSUE TITLE
Create an issue labeler workflow 

### ISSUE THREAD

**Issue by OBITORASU** [GDSC-RCCIIT/General-Purpose-Scripts#58]
## Suggest an improvement 
Currently we manually assign labels to issues, I want a workflow which does that for us every time an issue is created.

### Describe the solution you'd like
We can use this [action](https://github.com/github/issue-labeler) for example. We have some keyword in our issues templates which you can use for the regex matching for the workflow, they can be found under the `.github` directory.

### Describe alternatives you've considered
You can use any other action for this as long as it works. But make sure you test it on your fork before creating a PR.

## Do you want to work on this?
- [ ] yes
- [x] no

**Comment by saaiiravi** [comment]
Can I work on this?

**Comment by OBITORASU** [comment]
Sure feel free.

**Comment by saaiiravi** [comment]
Yes. So I was facing difficulty catching the keywords. Can you help me out here?

**Comment by OBITORASU** [comment]
Use regex to match some of the keywords used in our issue template. You can check the template out its inside the `.github` directory.
