### ISSUE TITLE
SMS Sending Script Using Kalyra API

### ISSUE THREAD

**Issue by advaita-saha** [GDSC-RCCIIT/General-Purpose-Scripts#60]
SMS Sending Script Using Kalyra API

This is a python script that uses the kaleyra API for sending SMS. Kaleyra is one of the leading SMS service provider in the industry

Running the script provides users different kind of options for sending SMS. You can choose anyone and proceed with their SMS marketing campaign. This uses the Kaleyra API and make a nice CLI tool

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by advaita-saha** [comment]
Please assign this task to me

**Comment by OBITORASU** [comment]
Sure go ahead.
