### ISSUE TITLE
Reddit Image Scraper

### ISSUE THREAD

**Issue by OBITORASU** [GDSC-RCCIIT/General-Purpose-Scripts#63]
### Describe the new script you want
I want a script which scrapes top images from a subreddit of choice, e.g. `r/wallpapers` and stores them on your PC preferably in `.png` or `.jpg` format.

### Describe the solution you'd like us to follow
You should be using the `.json` method for scraping instead of the reddit api. You can parson the .json response and grab the url for the images and download them on the local system.

## Do you want to work on this?
- [ ] yes
- [x] no

**Comment by belelaritra** [comment]
I would like to work on this issue.

**Comment by OBITORASU** [comment]
Go ahead!
