### ISSUE TITLE
GUI Paint Application

### ISSUE THREAD

**Issue by adityamittl** [GDSC-RCCIIT/General-Purpose-Scripts#65]
## Suggest a new script for the project
GUI Paint application

### Describe the new script you want
Paint app using PyQt5 library

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by OBITORASU** [comment]
I think paint applications are way too common for most Operating Systems and having a full blown paint GUI paint application in a general purpose scripts repository doesn't make much sense. Closing this one.
