### ISSUE TITLE
OCR: Extract text from a valid image file

### ISSUE THREAD

**Issue by OBITORASU** [GDSC-RCCIIT/General-Purpose-Scripts#66]
### Describe the new script you want
A script to extract text from images and organize them in a `.txt` file (OCR)

### Describe the solution you'd like us to follow
Get a valid image from the user as input. Check if the image has any text, if not return an error. On the other hand, if there is valid text in the image provided by the user, scan the text content from the image and store them in an organized way in a `.txt` file.

## Do you want to work on this?
- [ ] yes
- [x] no

**Comment by Harshil-Jani** [comment]
I want to work with this Issue  ! Can I try ?

**Comment by OBITORASU** [comment]
Sure give it a go!

**Comment by xtanion** [comment]
I would like to work on it, Can I give it a try?

**Comment by OBITORASU** [comment]
@xtanion we have @Harshil-Jani working on this already.

**Comment by xtanion** [comment]
Okay, No problem. I just got little excited

**Comment by OBITORASU** [comment]
You can always open an issue of your own and work on it :)

**Comment by OBITORASU** [comment]
If you have any great ideas feel free to drop a Script Request and I will assign it to you.
