### ISSUE TITLE
Raspberry Pi  Telegram Bot

### ISSUE THREAD

**Issue by Saket37** [GDSC-RCCIIT/General-Purpose-Scripts#68]
### Describe the new script you want
A telegram Bot to monitor Raspberry Pi.

### Describe the solution you'd like us to follow
A script which will send CPU Temp alerts on Telegram. Shutdown, Reboot and Memory Usage of Raspberry Pi using Bot Commands. 

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by Saket37** [comment]
can I work on it?

**Comment by OBITORASU** [comment]
Don't think a script specific to `Rasberry Pi` can be considered `General Purpose`. Closing this, meanwhile if you have any other ideas feel free to open another issue :)
