### ISSUE TITLE
Youtube Video Downloader

### ISSUE THREAD

**Issue by advaita-saha** [GDSC-RCCIIT/General-Purpose-Scripts#69]
### Describe the new script you want
A simple YouTube video downloader from url as input and a working GUI

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by advaita-saha** [comment]
I want to contribute the script. Assign me this task

**Comment by rijusougata13** [comment]
go ahead @advaita-saha !

**Comment by OBITORASU** [comment]
@advaita-saha sorry to interrupt but our repository does not accept YouTube download scripts because it is against YouTube Terms of Service. I will have to unassign you and close this poor. Extremely sorry!
