### ISSUE TITLE
Video to Gif using python

### ISSUE THREAD

**Issue by aniketartani** [GDSC-RCCIIT/General-Purpose-Scripts#70]
I want to add the script of a program in python which can convert a video to gif. Please assign me
## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by OBITORASU** [comment]
Go ahead!

**Comment by saRvaGnyA** [comment]
Hey, can I work on this?

**Comment by kiranbaby14** [comment]
may i work on this ?

**Comment by OBITORASU** [comment]
Sure

**Comment by kiranbaby14** [comment]
thanks
