### ISSUE TITLE
Image Compressor

### ISSUE THREAD

**Issue by advaita-saha** [GDSC-RCCIIT/General-Purpose-Scripts#76]
### Describe the new script you want
Compresses large images into smaller file sizes

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by advaita-saha** [comment]
I want to contribute this script. Please assign me @OBITORASU

**Comment by OBITORASU** [comment]
Go ahead!

**Comment by OBITORASU** [comment]
@advaita-saha  When you write Fixes #(issue number) GitHub auto links the PR to the corresponding Issue and closes it once the PR is merged, I think you messed up by writing Issue #(issue number)
