### ISSUE TITLE
Reddit post scraper

### ISSUE THREAD

**Issue by DCYPHERR** [GDSC-RCCIIT/General-Purpose-Scripts#77]
## Suggest a new script for the project
Reddit scraper using old reddit. Exports data to csv.
Following are the fields that are exported
Post Date, Author, upvotes, link of the post 

### Describe the new script you want
A clear and concise description of what the new script is all about. Ex. I want an email script which [...]

### Describe the solution you'd like us to follow
A clear and concise description of how you want this script to work.

## Do you want to work on this?
- [ x] yes
- [ ] no

### Additional context
Add any other context or screenshots about the feature request here. If not applicable remove this section.

**Comment by OBITORASU** [comment]
Go ahead!

**Comment by DCYPHERR** [comment]
I'd like to work on the aforementioned. Kindly assign me the task!
