### ISSUE TITLE
Currency Converter

### ISSUE THREAD

**Issue by ichbinprashant** [GDSC-RCCIIT/General-Purpose-Scripts#8]
### Describe the new script you want
A real time GUI currency converter where value of one currency can be converted to that of another one in accordance to the exchange rate.

### Describe the solution you'd like us to follow
Refer to the image provided 

## Do you want to work on this?
- [ ] yes
- [ no ] no

### Additional context
![image](https://user-images.githubusercontent.com/33893505/135533108-59e3074c-f380-42ee-ac2b-95d400d73c2c.png)

**Comment by OBITORASU** [comment]
Great idea

**Comment by Stig124** [comment]
Can I work on that?

**Comment by OBITORASU** [comment]
Yes you can!

**Comment by jayaganeshkumar** [comment]
@OBITORASU Hey, do you want any script which collects the details of Crypto Currencies and displays all the details of a particular crypto coin? The details will be stored in a CSV file.

**Comment by OBITORASU** [comment]
@jayaganeshkumar make an issue and I will have it assigned

**Comment by jayaganeshkumar** [comment]
@OBITORASU I made an issue. Check it out

**Comment by Stig124** [comment]
I'm removing myself, I have way too little knowledge in Python GUIs

**Comment by belelaritra** [comment]
I would like to work on this issue.

**Comment by OBITORASU** [comment]
Go ahead!
