### ISSUE TITLE
Create JSON files from YAML files in a directory

### ISSUE THREAD

**Issue by antoooks** [GDSC-RCCIIT/General-Purpose-Scripts#82]
### Describe the new script you want
I would like to add a script to create JSON files from YAML files in a directory. Not converting, but instead adding new files with the same name only in JSON format.

### Describe the solution you'd like us to follow
To do list:
- Iterate YAML files
- Convert YAML files into JSON files
- Save JSON files in the same directory using the same file name

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by OBITORASU** [comment]
Go ahead!

**Comment by antoooks** [comment]
Hi I would like to work on this @OBITORASU :)
