### ISSUE TITLE
Text to Handwritten

### ISSUE THREAD

**Issue by GOD-OF-FIRE** [GDSC-RCCIIT/General-Purpose-Scripts#83]
I want to add a mini project which converts Text-to-handwritten image. It can converts text content to an image that looks like handwriting. 
Please assign this issue to me.

**Comment by OBITORASU** [comment]
Go ahead but next time try to follow the Issue template :)

**Comment by kiranbaby14** [comment]
can i work on this issue as part of hacktoberfest.

**Comment by Annnesha** [comment]
Can you assign this to me?
Thanks :)

**Comment by OBITORASU** [comment]
@kiranbaby14 assigning this to you since you asked first.

**Comment by kiranbaby14** [comment]
> @kiranbaby14 assigning this to you since you asked first.

Thank u
