### ISSUE TITLE
Word Cloud Generator

### ISSUE THREAD

**Issue by Candida18** [GDSC-RCCIIT/General-Purpose-Scripts#87]
### Code Description
This code generates a Word Cloud
Word Cloud is a data visualization technique used for representing text data in which the size of each word indicates its frequency or importance. Significant textual data points can be highlighted using a word cloud. Word clouds are widely used for analyzing data from social network websites.

### Description of the solution 
Import required libraries
Upload a txt file
The main function
Display the Word Cloud

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by Candida18** [comment]
> Thank you for opening your first issue in our repository, one of our maintainers will get in touch with you soon.

Please assign this issue to me(Candida18). I would like to work on it.

**Comment by OBITORASU** [comment]
Go ahead 3rd time is the charm!

**Comment by Candida18** [comment]
I have added a pull request. Please review it

**Comment by Candida18** [comment]
I have added a pull request with the necessary changes. Please review it

**Comment by Candida18** [comment]
I have added a pull request with the necessary changes. Please review it

**Comment by Candida18** [comment]
I have added a pull request with the necessary changes. Please review it
