### ISSUE TITLE
Spotify/Youtube playlist & songs downloader

### ISSUE THREAD

**Issue by xtanion** [GDSC-RCCIIT/General-Purpose-Scripts#91]
### Download songs from Spotify or YouTube link
The script will download songs or songs of a playlist, from a Youtube/Spotify link.

### Description
import libraries (FFmpeg or youtube-dl)
run downloader.py
paste the link in the terminal

## Do you want to work on this?
- [ ] yes
- [ ] no

**Comment by xtanion** [comment]
I would like to write a script that will minimize the steps of downloading a song. Please assign it to me 😃

**Comment by OBITORASU** [comment]
I can't assign download scripts like these to anyone in question because they are in violation of the ToS of the platforms mentioned sorry :(
Please make a new issue with some other idea if you still want to contribute.
