### ISSUE TITLE
Convert Word file to PDF format

### ISSUE THREAD

**Issue by BasuDevTyagi10** [GDSC-RCCIIT/General-Purpose-Scripts#92]
### Code Description
Python script that converts doc file to pdf format. Comes handy when you have a bulk or single file conversion!

### Description of the solution
using docx2pdf module for file conversion and tkinter for GUI which enables easy use for the end user.

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by BasuDevTyagi10** [comment]
I would like to work on this issue for hacktoberfest2021. Please assign this issue to me.

**Comment by OBITORASU** [comment]
Go ahead!

**Comment by k-chetan** [comment]
I want to work on this issue.

**Comment by Ritika457** [comment]
Hey, @BasuDevTyagi10  , I would like to work on this issue for hacktoberfest2021. Please assign this issue to me.

**Comment by BasuDevTyagi10** [comment]
hi @Ritika457, sorry but I cannot assign you the issue since I'm not a moderator of this repo and also I've already made a PR for this issue (need to fix some merge conflicts though). I suggest you create your own issue and work on it.. that's how I did things here.. All the best.
