### ISSUE TITLE
merge pdf according to order

### ISSUE THREAD

**Issue by dawnblade97** [GDSC-RCCIIT/General-Purpose-Scripts#93]
### Describe the new script you want
A script that would merge all the pdf in a specific directory giving the user liberty to chose order

### Describe the solution you'd like us to follow
the script would first find all the pdf in a specific directory and then ask the user to order them if they want to . 

## Do you want to work on this?
- [x] yes
- [ ] no

**Comment by OBITORASU** [comment]
Go ahead! One of those scripts even I might end up using :P
